### ISSUE TITLE
Instrução inconsistente com o Github.

### ISSUE THREAD

**Issue by roger-russel** [devconductor/desafio-golang#2]
Senhores,

Gostaria de sugerir a alteração na instrução 1 do Readme 

De:

```
1. Faça um fork deste repositório, torne ele privado, desenvolva a sua solução e comit dentro desse seu repositório.
```

Para:

```
1. Duplique esse repositório para um repositório privado, desenvolva a sua solução e commit dentro desse seu repositório.
```
Isto por que não e possível alterar a visibilidade de um fork no Github fazendo com que a linha em sí não possível de ser realizada.

![print from github](https://i.ibb.co/3cMXQR4/duplicate.png)

https://docs.github.com/articles/duplicating-a-repository

**Comment by thiagossampaio** [comment]
Feito
